module.exports = {
    TWILIO_ACCOUNTSID: process.env.TWILIO_ACCOUNTSID,
    TWILIO_AUTHTOKEN: process.env.TWILIO_AUTHTOKEN,
    NEXMO_APIKEY: process.env.NEXMO_APIKEY,
    NEXMO_APISECRET: process.env.NEXMO_APISECRET,
    NEXMO_APPLICATIONID: process.env.NEXMO_APPLICATIONID,
    MAILTRAP_USER: process.env.MAILTRAP_USER,
    MAILTRAP_PASS: process.env.MAILTRAP_PASS
};